### ISSUE TITLE
code flow is not created

### ISSUE THREAD

**Issue by devhyejin** [season-framework/dizest#3]
### **Describe the bug**
I tried to save the output name including spaces and words, I’ve got a following error message. "Output name only allow alphabet and digits." and the code flow for the app is not created.

![image](https://user-images.githubusercontent.com/85564080/186092576-b7081701-bfaa-46bf-83ce-e6dccd561323.png)

**Comment by proin** [comment]
applied dizest-ui version `v2022.08.23.1536`
